package comparator;

import java.io.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class CsvFile {
    String filePath;

    public CsvFile(String filePath) {
        this.filePath = filePath;
    }

    public static void CompareFileCsv(CsvFile actualFile, CsvFile ErrorExpectedFile) {
        Scanner sc=new Scanner(System.in);
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH-mm-ss-SSS");       //setting timestamp for// making a unique file each time we are comparing a file
        String formattedDateTime = now.format(formatter);
        boolean flag = false;                                                                    //flag to check  difference in the file
        try (BufferedReader ReaderActualFile1 = new BufferedReader(new FileReader(actualFile.filePath));
             BufferedReader ReaderErrorExpectedFile2 = new BufferedReader(new FileReader(ErrorExpectedFile.filePath))) {
            String Line1, Line2;
            ReaderActualFile1.readLine();                                                                      //reading the header of the file1
            ReaderErrorExpectedFile2.readLine();                                                                       //reading the header of the file2

            while ((Line1 = ReaderActualFile1.readLine()) != null) {                                          //storing each line in a String
                Line2 = ReaderErrorExpectedFile2.readLine();
                String[] data3 = Line1.split(",");                                          //making a String array generated by csv using , delimiter
                String[] data4 = Line2.split(",");
//
                for (int i = 0; i < data3.length; i++) {                                         //checking for any difference in the file
                    if (!(data3[i].equals(data4[i]))) {
                        flag = true;
                        break;


                    }
                }
                    if(flag)
                        break;

            }
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }

        if (flag) {                                                                                     //checking any difference is present or not
            try (BufferedReader ReaderActualFile3 = new BufferedReader(new FileReader(actualFile.filePath));                       //creating objects of reading and writing a new csv filling listing all the difference in the file
                 BufferedReader ReaderErrorExpectedFile4 = new BufferedReader(new FileReader(ErrorExpectedFile.filePath));
                 BufferedWriter writer = new BufferedWriter(new FileWriter("Result+" + formattedDateTime + ".csv"))) {


                String Line1, Line2;
                String Header = ReaderActualFile3.readLine();                                                                   //storing information of header in a String
                String[] header = Header.split(",");
                System.out.println("Enter the column name (header) you want to skip"); //taking a column name you want to skip
                String skip=sc.nextLine();
                int SkipCoolum=-1;
                for(int values=0;values<header.length;values++) {                                                 //traversing header to check header (column) to skip in comparison
                    if ( header[values].equals(skip))
                    {
                        SkipCoolum = values;
                        break;

                    }
                }
                ReaderErrorExpectedFile4.readLine();                                                                                  //reading the header of 2nd file without comparing



                int count = 1;
                writer.write("Location,Expected,False");                                                   //writing the header of new csv file (differences)

                while ((Line1 = ReaderActualFile3.readLine()) != null) {                                                      //reading both file line by line and storing in a String
                    Line2 = ReaderErrorExpectedFile4.readLine();
                    String[] data1 = Line1.split(",");
                    String[] data2 = Line2.split(",");                                                    //making String array storing values separated by , in csv file
                        for (int values = 0; values < data1.length; values++) {
                            if (!(data1[values].equals(data2[values])) && values!=SkipCoolum)                  //checking values in the array is not equal and skipped column
                            {
                                writer.write("\n");
                                writer.write("Row :" + (count + 1) + " Column : " + (values + 1) + "(" + header[values] + ")" + "," + data1[values] + "," + data2[values]);             //writing in the new csv File

                            }
                        }
                        count++;
                    }

                } catch (IOException e) {
                throw new RuntimeException(e);
            }
            System.out.println("Comparison of Csv file are Completed Successfully\nNew result File is Created : \n"+"Result"+formattedDateTime+".csv");

        }
        else
            System.out.println("Csv Files are Same Already");
    }
}